apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rapid-crayfish-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rapid-crayfish-nodejs 
  name: rapid-crayfish-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rapid-crayfish-nodejs 
